# Generated by Django 5.2.17 on 2026-08-29 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('method', models.CharField(choices=[('debit', 'Дебетовая карта'), ('wallet', 'Электронный кошелёк'), ('cod', 'Наложенный платёж')], max_length=16, verbose_name='способ')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('succeeded', 'Успешно'), ('failed', 'Отклонено')], default='pending', max_length=16, verbose_name='статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('transaction_id', models.CharField(blank=True, max_length=64, verbose_name='id транзакции')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='ошибка')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
                'ordering': ('-created_at',),
            },
        ),
    ]
