# Generated by Django 5.2.17 on 2026-08-29 21:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], db_index=True, default='pending', max_length=16, verbose_name='статус')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='сумма заказа')),
                ('shipping_address', models.TextField(verbose_name='адрес доставки')),
                ('contact_name', models.CharField(max_length=255, verbose_name='контактное лицо')),
                ('contact_phone', models.CharField(max_length=32, verbose_name='телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('payment_method', models.CharField(choices=[('debit', 'Дебетовая карта'), ('wallet', 'Электронный кошелёк'), ('cod', 'Наложенный платёж')], default='debit', max_length=16, verbose_name='способ оплаты')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='оплачен')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за единицу')),
            ],
            options={
                'verbose_name': 'позиция заказа',
                'verbose_name_plural': 'позиции заказа',
                'ordering': ('id',),
            },
        ),
    ]
